### 1. create user with invalid data (should fail)
POST http://localhost:4000/users
Content-Type: application/json

{
    "username": "u",
    "email": "testexample.com",
    "password":"1234"
}


### 2. create user with valid data (should succeed)
POST http://localhost:4000/users
Content-Type: application/json

{
    "username": "testuser1",
    "email": "testuser1@example.com",
    "password":"123456"
}


### 3. login with invalid data (should fail)
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username":"testuser2",
    "password":"123456"
}


### 4. login with valid data (should succeed)
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username":"testuser1@example.com",
    "password":"123456"
}


### 5. Get user info (needs auth if protected
GET http://localhost:4000/users


### 6. Update user email (optional: needs auth)
PUT http://localhost:4000/users
Content-Type: application/json

{
    "email":"testuser@example.com"
}


### 7. Create advert (should succeed)
POST http://localhost:4000/adverts
Content-Type: application/json

{
    "name": "Test Advert2",
    "description": "This is a test advert",
    "price": 100.0,
    "image": "http://example.com/image.jpg",
    "owner": "testuser",
    "tags":[""]
}


### 8. Get all adverts (should succeed)
GET http://localhost:4000/adverts


### 9. Update advert with invalid ID (should fail)
PUT http://localhost:4000/adverts/67ef9b6111c523d220177b5f
Content-Type: application/json

{
    "price": 200.0
}


### 10. Update advert with valid ID (should succeed - adjust ID dynamically if needed)
PUT http://localhost:4000/adverts/67ef9b9511c523d220177b63
Content-Type: application/json

{
    "price": 200.0
}


### 11. Delete advert from another user (should fail)
DELETE http://localhost:4000/adverts/67ef9b6111c523d220177b5f


### 12. Delete advert owned by current user (should succeed - adjust ID dynamically if needed)
DELETE http://localhost:4000/adverts/67ef9b9511c523d220177b63


### 13. Delete user (cleanup at the end)
DELETE http://localhost:4000/users