name: Deploy Wallaclone

on:
  workflow_call:
    secrets:
      AWS_HOST:
        required: true
      AWS_USER:
        required: true
      AWS_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Remove remote frontend folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 2405
          script: |
            sudo rm -rf /var/www/wallaclone-react
            sudo mkdir -p /var/www/wallaclone-react 
            sudo chown -R ${{ secrets.AWS_USER }}:${{ secrets.AWS_USER }} /var/www/wallaclone-react

      - name: Remove remote backend folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 2405
          script: |
            sudo rm -rf /home/apps/wallaclone-node
            sudo mkdir -p /home/apps/wallaclone-node
            sudo chown -R apps:apps /home/apps/wallaclone-node

      - name: Copy built frontend to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 2405
          source: "frontend/dist/"
          target: "/var/www/wallaclone-react/"

      - name: Copy backend to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 2405
          source: "backend/"
          target: "/home/apps/wallaclone-node/"

      # - name: Install backend dependencies
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.AWS_HOST }}
      #     username: ${{ secrets.AWS_USER }}
      #     key: ${{ secrets.AWS_SSH_KEY }}
      #     port: 2405
